/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  ComponentsBreakdown,  EndOfLifeAgentOutput,  EnergyConsumption,  FootprintContribution,  LifecycleAgentOutput,  ManufacturingAgentOutput,  ManufacturingLocation,  MaterialInfo,  MaterialsAgentOutput,  PackagingAgentOutput,  PackagingMaterial,  RecyclabilityInfo,  Repairability,  ShippingRoute,  SummaryAgentOutput,  TotalCarbonFootprint,  TransportAgentOutput } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface ComponentsBreakdown {
        highlyRecyclable?: (string | null)[]
        hardToRecycle?: (string | null)[]
    }
    
    export interface EndOfLifeAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        recyclability?: (partial_types.RecyclabilityInfo | null)
        commonDisposalMethods?: (Record<string, (string | null)> | null)
    }
    
    export interface EnergyConsumption {
        average?: (string | null)
        annualUsage?: (string | null)
        totalLifetimeEnergy?: (string | null)
        averageLifetimeEmissions?: (string | null)
    }
    
    export interface FootprintContribution {
        score?: (number | null)
        contribution?: (string | null)
    }
    
    export interface LifecycleAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        expectedLifespan?: (string | null)
        energyConsumption?: (partial_types.EnergyConsumption | null)
        repairability?: (partial_types.Repairability | null)
    }
    
    export interface ManufacturingAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        manufacturingLocations?: (partial_types.ManufacturingLocation | null)[]
    }
    
    export interface ManufacturingLocation {
        country?: (string | null)
        city?: (string | null)
        facilityType?: (string | null)
        energySources?: (string | null)[]
        emissions?: (string | null)
        certifications?: (string | null)[]
    }
    
    export interface MaterialInfo {
        name?: (string | null)
        percentage?: (number | null)
        carbonIntensity?: (string | null)
        recyclability?: (string | null)
        sourceInfo?: (string | null)
    }
    
    export interface MaterialsAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        materials?: (partial_types.MaterialInfo | null)[]
        totalRecyclablePercentage?: (number | null)
        materialsRenewablePercentage?: (number | null)
    }
    
    export interface PackagingAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        packagingMaterials?: (partial_types.PackagingMaterial | null)[]
        packagingWeight?: (string | null)
        biodegradablePercentage?: (number | null)
    }
    
    export interface PackagingMaterial {
        material?: (string | null)
        percentage?: (number | null)
        recyclability?: (string | null)
        carbonFootprint?: (string | null)
        sourceInfo?: (string | null)
    }
    
    export interface RecyclabilityInfo {
        overallScore?: (string | null)
        componentsBreakdown?: (partial_types.ComponentsBreakdown | null)
    }
    
    export interface Repairability {
        score?: (string | null)
        limitations?: (string | null)[]
    }
    
    export interface ShippingRoute {
        origin?: (string | null)
        destination?: (string | null)
        method?: (string | null)
        distance?: (string | null)
        emissionsPerUnit?: (string | null)
    }
    
    export interface SummaryAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        totalCarbonFootprint?: (partial_types.TotalCarbonFootprint | null)
        keyImpactAreas?: (string | null)[]
        positiveSustainabilityAspects?: (string | null)[]
        consumerRecommendation?: (string | null)
        sustainabilityImprovementPotential?: (string | null)
        similarProductsWithBetterScores?: (string | null)[]
        improvementRecommendations?: (string | null)[]
    }
    
    export interface TotalCarbonFootprint {
        score?: (number | null)
        classification?: (string | null)
        breakdown?: (Record<string, (partial_types.FootprintContribution | null)> | null)
        comparativeRanking?: (string | null)
    }
    
    export interface TransportAgentOutput {
        details?: (string | null)
        carbonScore?: (number | null)
        primaryShippingRoutes?: (partial_types.ShippingRoute | null)[]
        totalTransportEmissions?: (string | null)
    }
    
}